<?php

namespace Proxies\__CG__\abmestadisticas\abmBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fallo extends \abmestadisticas\abmBundle\Entity\Fallo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'abmestadisticas\\abmBundle\\Entity\\Fallo' . "\0" . 'fallId', '' . "\0" . 'abmestadisticas\\abmBundle\\Entity\\Fallo' . "\0" . 'fallAnio', '' . "\0" . 'abmestadisticas\\abmBundle\\Entity\\Fallo' . "\0" . 'fallDivision', '' . "\0" . 'abmestadisticas\\abmBundle\\Entity\\Fallo' . "\0" . 'fallDetalle', '' . "\0" . 'abmestadisticas\\abmBundle\\Entity\\Fallo' . "\0" . 'fallLink');
        }

        return array('__isInitialized__', '' . "\0" . 'abmestadisticas\\abmBundle\\Entity\\Fallo' . "\0" . 'fallId', '' . "\0" . 'abmestadisticas\\abmBundle\\Entity\\Fallo' . "\0" . 'fallAnio', '' . "\0" . 'abmestadisticas\\abmBundle\\Entity\\Fallo' . "\0" . 'fallDivision', '' . "\0" . 'abmestadisticas\\abmBundle\\Entity\\Fallo' . "\0" . 'fallDetalle', '' . "\0" . 'abmestadisticas\\abmBundle\\Entity\\Fallo' . "\0" . 'fallLink');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fallo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFallId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getFallId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFallId', array());

        return parent::getFallId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFallAnio($fallAnio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFallAnio', array($fallAnio));

        return parent::setFallAnio($fallAnio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFallAnio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFallAnio', array());

        return parent::getFallAnio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFallDivision($fallDivision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFallDivision', array($fallDivision));

        return parent::setFallDivision($fallDivision);
    }

    /**
     * {@inheritDoc}
     */
    public function getFallDivision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFallDivision', array());

        return parent::getFallDivision();
    }

    /**
     * {@inheritDoc}
     */
    public function setFallDetalle($fallDetalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFallDetalle', array($fallDetalle));

        return parent::setFallDetalle($fallDetalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getFallDetalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFallDetalle', array());

        return parent::getFallDetalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setFallLink($fallLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFallLink', array($fallLink));

        return parent::setFallLink($fallLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getFallLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFallLink', array());

        return parent::getFallLink();
    }

}
